

export const codeSourceDemo = `
:PROGRAM_START

:CREATE_COMMAND
CALL $WRITE_FILENAME
MOV_A_IMM 0x91 # Commande CREATE
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_COMMAND
MOV_A_MEM MEMORY_MAP.DATA_DISK_FS_COMMAND # Vérifier résultat
JZ $END # Si échec, halt

:OPEN_FILE
CALL $WRITE_FILENAME
MOV_A_IMM 0x92 # Command OPEN
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_COMMAND

:WRITE_FILE_CONTENT
MOV_B_IMM 0x25 # initialise la taille du contenu a lire (hardcodé)
MOV_A_IMM 0x00
MOV_MEM_A MEMORY_MAP.DATA_DISK_2_ADDR_LOW   # initialise position dans le contenu à parcourir - low
MOV_MEM_A MEMORY_MAP.DATA_DISK_2_ADDR_HIGH  # initialise position dans le contenu à parcourir - high

:WRITE_FILE_CONTENT_LOOP
MOV_C_MEM MEMORY_MAP.DATA_DISK_2_DATA # Read dataDisk2 (raw)
MOV_MEM_C MEMORY_MAP.DATA_DISK_FS_DATA # Write dataDisk (fs)
INC_A
MOV_MEM_A MEMORY_MAP.DATA_DISK_2_ADDR_LOW   # update position dans le contenu à parcourir - low
PUSH_A
SUB
POP_A
JNZ $WRITE_FILE_CONTENT_LOOP

:CLOSE_FILE
MOV_A_IMM 0x93 # Command CLOSE
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_COMMAND

:PLAY_SOUND
MOV_A_IMM 45 # Fréquence = 440 Hz → valeur ≈ (440-100)/7.45 ≈ 45
MOV_MEM_A MEMORY_MAP.BUZZER_FREQ
MOV_A_IMM 50 # Durée = 500ms → 500/10 = 50
MOV_MEM_A MEMORY_MAP.BUZZER_DURATION # déclenche le son

:EXECUTE_FILE
# TODO: charger le fichier en RAM puis l'executer
JMP $END

:WRITE_FILENAME
MOV_A_IMM 0x54 # "T"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x45 # "E"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x53 # "S"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x54 # "T"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x2E # "."
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x54 # "T"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x58 # "X"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x54 # "T"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
RET

:END
SYSCALL 0
`;


export default codeSourceDemo;

