#!/bin/bash


cd `dirname $0`


# Build for prod
#npx asc index.ts -o ../build/release.wasm

# Build for dev
npx asc index.ts -o ../build/release.wasm -t ../build/release.wat --debug --sourceMap --exportRuntime

