
PROGRAM_START:
INIT:

MAIN:
    MOV_A_IMM 0x01
    MOV_MEM_A MEMORY_MAP.LCD_COMMAND

    START:
        CALL $LEDS_ON # Go to LEDS_ON
        MOV_A_IMM 0x0F # A = Delay counter for WAIT_LOOP
        CALL $WAIT_LOOP # Go to WAIT_LOOP
        CALL $LEDS_OFF # Go to LEDS_OFF
        JMP $END # Go to END

    END:
    #SYSCALL 0x00
    RET


LEDS_ON:
    MOV_A_IMM 0xFF
    MOV_MEM_A MEMORY_MAP.LEDS_BASE
    RET

WAIT_LOOP:
    DEC_A
    JNZ $WAIT_LOOP
    RET

LEDS_OFF:
    MOV_A_IMM 0x00
    MOV_MEM_A MEMORY_MAP.LEDS_BASE
    RET

