

export const codeSourceDemo = `
:PROGRAM_START

:CREATE_COMMAND
CALL $WRITE_FILENAME
MOV_A_IMM 0x91 # Commande CREATE
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_COMMAND
MOV_A_MEM MEMORY_MAP.DATA_DISK_FS_COMMAND # Vérifier résultat
JZ $END # Si échec, halt

:OPEN_FILE
CALL $WRITE_FILENAME
MOV_A_IMM 0x92 # Command OPEN
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_COMMAND

:WRITE_FILE_CONTENT
${new Array(3).fill(null).map((_, idx) => `
MOV_A_IMM 0x48 # 'H'
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_DATA
MOV_A_IMM 0x65 # 'e'
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_DATA
MOV_A_IMM 0x6C # 'l'
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_DATA
MOV_A_IMM 0x6C # 'l'
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_DATA
MOV_A_IMM 0x6F # 'o'
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_DATA
MOV_A_IMM 0x0A # '\n
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_DATA
`).join('\n\n')}

:CLOSE_FILE
MOV_A_IMM 0x93 # Command CLOSE
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_COMMAND

:PLAY_SOUND
MOV_A_IMM 45 # Fréquence = 440 Hz → valeur ≈ (440-100)/7.45 ≈ 45
MOV_MEM_A MEMORY_MAP.BUZZER_FREQ
MOV_A_IMM 50 # Durée = 500ms → 500/10 = 50
MOV_MEM_A MEMORY_MAP.BUZZER_DURATION # déclenche le son
JMP $END

:WRITE_FILENAME
MOV_A_IMM 0x54 # "T"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x45 # "E"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x53 # "S"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x54 # "T"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x2E # "."
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x54 # "T"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x58 # "X"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
MOV_A_IMM 0x54 # "T"
MOV_MEM_A MEMORY_MAP.DATA_DISK_FS_FILENAME
RET

:END
SYSCALL 0
`;


export default codeSourceDemo;

