
CONSOLE_HELLO_WORLD:

    MOV_A_IMM 0x48 # H
    MOV_MEM_A @CONSOLE_BASE

    MOV_A_IMM 0x65 # e
    MOV_MEM_A @CONSOLE_BASE

    MOV_A_IMM 0x6C # l
    MOV_MEM_A @CONSOLE_BASE

    MOV_A_IMM 0x6C # l
    MOV_MEM_A @CONSOLE_BASE

    MOV_A_IMM 0x6F # o
    MOV_MEM_A @CONSOLE_BASE

    MOV_A_IMM 0x20 # SPACE
    MOV_MEM_A @CONSOLE_BASE

    MOV_A_IMM 0x57 # W
    MOV_MEM_A @CONSOLE_BASE

    MOV_A_IMM 0x6F # o
    MOV_MEM_A @CONSOLE_BASE

    MOV_A_IMM 0x72 # r
    MOV_MEM_A @CONSOLE_BASE

    MOV_A_IMM 0x6C # l
    MOV_MEM_A @CONSOLE_BASE

    MOV_A_IMM 0x64 # d
    MOV_MEM_A @CONSOLE_BASE

    MOV_A_IMM 0x21 # !
    MOV_MEM_A @CONSOLE_BASE

    MOV_A_IMM 0x0A # EOF
    MOV_MEM_A @CONSOLE_BASE

    RET

